"""
Django settings for products project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4c-2=&@=ll11g(x#t95$v-lsg%+mlo9kx-6tkx)149otm_$)w='

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
#     'django.template.loaders.eggs.Loader',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'pinax_theme_bootstrap_account',
    'machine',
    'eztables',
    'djangojs',
    'eztables.demo',
    'simple',
    'multiupload',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',
)

ROOT_URLCONF = 'products.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.account',
            ],
        },
    },
]

WSGI_APPLICATION = 'products.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'products',
        'USER':'root',
        'PASSWORD':'root',
        'HOST':'',
        'PORT':'',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'shahidgadda1@gmail.com'
EMAIL_HOST_PASSWORD = 'dbkpyjrvkofbxfhh'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ACCOUNT_OPEN_SIGNUP = True

ACCOUNT_LOGIN_URL = "account_login"

ACCOUNT_SIGNUP_REDIRECT_URL = "/"

ACCOUNT_LOGIN_REDIRECT_URL = "/"

ACCOUNT_LOGOUT_REDIRECT_URL = "/"

ACCOUNT_PASSWORD_CHANGE_REDIRECT_URL = "account_password"

ACCOUNT_PASSWORD_RESET_REDIRECT_URL = "account_login"

ACCOUNT_REMEMBER_ME_EXPIRY = 60 * 60 * 24 * 365 * 10

ACCOUNT_USER_DISPLAY = lambda user: user.username

ACCOUNT_CREATE_ON_SAVE = True

ACCOUNT_EMAIL_UNIQUE = True

ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False

ACCOUNT_EMAIL_CONFIRMATION_EMAIL = True

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_login"

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None

ACCOUNT_EMAIL_CONFIRMATION_URL = "account_confirm_email"

ACCOUNT_SETTINGS_REDIRECT_URL = "account_settings"

ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE = True

ACCOUNT_DELETION_MARK_CALLBACK = "account.callbacks.account_delete_mark"

ACCOUNT_DELETION_EXPUNGE_CALLBACK = "account.callbacks.account_delete_expunge"

ACCOUNT_DELETION_EXPUNGE_HOURS = 48

ACCOUNT_HOOKSET = "account.hooks.AccountDefaultHookSet"


ACCOUNT_USE_AUTH_AUTHENTICATE = False




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/home/shahid/workspace/projects/products/pinax_theme_bootstrap_account/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/shahid/workspace/projects/products/media/'